name: "Govulncheck Action"
description: "Run Go vulerability checker"
author: "Kevin Mulvey"
inputs:
  packages:
    description: 'Run govulncheck on these packages.'
    required: false
    default: './...'

runs:
  using: 'composite'
  steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Set up Go 
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - name: Run govulncheck
      run: govulncheck ${{ inputs.packages }}
      shell: bash

branding:
  icon: 'alert-triangle'
  color: 'red'
